### ISSUE TITLE
The package in the npm.com is outdated; this package is still maintained?

### ISSUE THREAD

**Issue by niwinz** [filipesilva/clj-kondo#5]
Related: https://github.com/borkdude/clj-kondo/issues/1083

**Comment by filipesilva** [comment]
Heya @niwinz and @borkdude, yeah this package is very outdated. I'm using clj-kondo directly nowadays so I haven't kept it up to date.

I'm making a new release now but the real problem is that this needs to happen manually. I should be able to make a Github Action that runs every week and checks what the latest clj-kondo version is, then makes a new release of this package. 

Would be even better if there's a ready-made github action for that.

**Comment by borkdude** [comment]
@filipesilva We could also deprecate this package if nobody is using it or if there are better and more up to date alternatives. How are you using it nowadays?

**Comment by filipesilva** [comment]
I'm mostly using it directly from the binary from within a linux container. 

I still include it in https://github.com/filipesilva/create-cljs-app because it's more straightforward than adding a separate step do download it. 

Have considered moving it to `deps.edn` and running clj-kondo via an alias, but deps.edn setups on windows are still kinda bad I feel, because clojure on windows is a powershell script and that makes it super weird to use with other terminals.

**Comment by borkdude** [comment]
@filipesilva I have a solution for Windows: 

https://github.com/borkdude/deps.clj

The binary deps.exe is also installable via scoop.

**Comment by filipesilva** [comment]
That does sound interesting, but does shadow-cljs use it if available? If it doesn't then it ends up being a separate thing. 

Which might be ok, but suddenly generic setup for new users includes a lot more explanations and steps.

**Comment by borkdude** [comment]
I haven't used shadow-cljs a lot myself, so I have no idea.

**Comment by borkdude** [comment]
@filipesilva Is it an option to remove this clj-kondo package from npm? I'd rather have it removed than keeping behind the latest releases, since this is confusing users (I keep getting questions about it).

**Comment by filipesilva** [comment]
@borkdude I'm very sorry, I've been terrible in responding to this. You're right that being behind is worse than being removed (or deprecated, which I think is what would really happen on npm).

I think the options for keeping it up to date are somewhere along these lines:
1. I setup a way for this repo to auto update
2. We move this functionality into the clj-kondo repository itself

I imagine you aren't very interested in 2. but am just throwing it out there just in case. I've recently had to work on a cron job running on github actions so maybe I can do something similar for 1. The hard part about 1. for me is actually taking the time to do it, so let's say there's a 2 week deadline and I either do it or deprecate this package.

**Comment by filipesilva** [comment]
I think this package should always be up to date now. I've added https://github.com/filipesilva/clj-kondo/blob/master/.github/workflows/release-sync.yml, which is a github action triggered every sunday that will check the latest clj-kondo version and if it is more recent, update and release this package.

@borkdude do you think once per week is enough, or would you prefer a higher frequency?

**Comment by borkdude** [comment]
Once a week seems sufficient to me. Thanks!
